### ISSUE TITLE
Opengl error due to incompatibility with mr crayfish guns mod

### ISSUE THREAD

**Issue by NighthowlerStudios** [DaDerpDuck/Seamless-Loading-Screen-Forge#8]
The following error is thrown when saving a screenshot whilst exiting the world.  It causes a slight hitch in framerates but no crash.

[17:54:03] [main/ERROR]: OpenGL API ERROR: 1281 (GL_INVALID_VALUE error generated. Size and/or offset out of range.)
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL11C.glCopyTexSubImage2D(Native Method) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL11.glCopyTexSubImage2D(GL11.java:7192) [lwjgl-opengl-3.2.2.jar:build 10]
	at com.mrcrayfish.guns.client.render.ScreenTextureState.onRenderWorldLast(ScreenTextureState.java:92) [?:1.1.0-1.16.5]
	at com.mrcrayfish.guns.client.render.ScreenTextureState$$Lambda$27398/880003033.accept(Unknown Source) [?:1.1.0-1.16.5]

**Comment by DaDerpDuck** [comment]
Can't seem to replicate the issue. Can you send your debug log?

**Comment by NighthowlerStudios** [comment]
a debug log was not provided.  all I can send is latest
[latest.log](https://github.com/DaDerpDuck/Seamless-Loading-Screen-Forge/files/7836173/latest.log)

**Comment by NighthowlerStudios** [comment]
I also have nicephore, advancement plaques and optifine installed, all of which change some screenshot mixins/shaders.  nicephore especially.

**Comment by DaDerpDuck** [comment]
Still can't replicate
Tbh that error could be caused by another mod. The hitch in framerate, though, could just be an effect as the screenshot is being taken (a similar hitch is also observed just by pressing the screenshot button). You could try this [previously unpublished build here](https://github.com/DaDerpDuck/Seamless-Loading-Screen-Forge/releases/tag/v1.1.7%2B1.16forge) though, which makes the file writing operation asynchronous. Theoretically should increase performance as Minecraft doesn't need to wait for the file to save, but I wasn't able to notice a difference.
Mod versions for 1.17+ already have this asynchronous file writing - I just didn't backport it to 1.16 since I was unsure if it helped or not.

**Comment by NighthowlerStudios** [comment]
the version is for 1.16.5.  yes I would like to see a build that makes screenshots asynchronous made public. the hitches get nasty

**Comment by DaDerpDuck** [comment]
Published
